// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtR3aH4FtU81lNRU12xhyax1--i6kmAVg',
    appId: '1:672727875549:web:a7896a1fa77a8a6fc8c034',
    messagingSenderId: '672727875549',
    projectId: 'todoi-todolist',
    authDomain: 'todoi-todolist.firebaseapp.com',
    databaseURL: 'https://todoi-todolist-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todoi-todolist.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuB8ufEJj95Pcs_iGEXV_Obm4M4N444zo',
    appId: '1:672727875549:android:315da4ef42485dd0c8c034',
    messagingSenderId: '672727875549',
    projectId: 'todoi-todolist',
    databaseURL: 'https://todoi-todolist-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todoi-todolist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC53chBUSyhiaz-I5g-DCD5FaBUPIdi3MQ',
    appId: '1:672727875549:ios:76f3d1614fc18939c8c034',
    messagingSenderId: '672727875549',
    projectId: 'todoi-todolist',
    databaseURL: 'https://todoi-todolist-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todoi-todolist.appspot.com',
    androidClientId: '672727875549-dqkdcd9q6vp9l756lm44qbo508olns7a.apps.googleusercontent.com',
    iosClientId: '672727875549-arnbiu9s3htbd43d4fcnjtc1dgp928vf.apps.googleusercontent.com',
    iosBundleId: 'com.byIcho.toDoi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC53chBUSyhiaz-I5g-DCD5FaBUPIdi3MQ',
    appId: '1:672727875549:ios:536f82b5c8d99deac8c034',
    messagingSenderId: '672727875549',
    projectId: 'todoi-todolist',
    databaseURL: 'https://todoi-todolist-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todoi-todolist.appspot.com',
    androidClientId: '672727875549-dqkdcd9q6vp9l756lm44qbo508olns7a.apps.googleusercontent.com',
    iosClientId: '672727875549-euhp51kld2brln81csqqsqnhbjvsn524.apps.googleusercontent.com',
    iosBundleId: 'com.byIcho.toDoList',
  );
}
